import { StyleSheet } from 'react-native'

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#F8FAF7' },
  content: { paddingHorizontal: 24, paddingTop: 8, paddingBottom: 32 },
  topbar: { minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 12 },
  backButton: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center' },
  backButtonPressed: { backgroundColor: '#EAF6E4' },
  topbarTitle: { flex: 1, color: '#151A15', fontSize: 17, textAlign: 'center' },
  topbarSpacer: { width: 44, height: 44 },
  timerHero: { alignItems: 'center', paddingTop: 30, paddingBottom: 24 },
  modeToggleContainer: { width: '100%', marginBottom: 18, alignItems: 'center' },
  modeToggle: { width: '100%', minHeight: 46, padding: 4, flexDirection: 'row', gap: 4, borderRadius: 14, backgroundColor: '#EAF1E9' },
  modeOption: { flex: 1, minHeight: 38, alignItems: 'center', justifyContent: 'center', borderRadius: 10 },
  modeOptionActive: { backgroundColor: '#FFFFFF', shadowColor: '#152914', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.08, shadowRadius: 4, elevation: 1 },
  modeOptionDisabled: { opacity: 0.45 },
  modeOptionPressed: { opacity: 0.72 },
  modeOptionText: { color: '#697269', fontSize: 13, fontWeight: '700' },
  modeOptionTextActive: { color: '#438C31', fontWeight: '800' },
  modeHint: { marginTop: 8, color: '#697269', fontSize: 11, textAlign: 'center' },
  timerLabel: { color: '#697269', fontSize: 13 },
  timerCircle: { width: 250, height: 250, marginTop: 14, marginBottom: 26, alignItems: 'center', justifyContent: 'center' },
  timerSvg: { position: 'absolute', top: 0, left: 0 },
  timerCircleInner: { width: 230, height: 230, borderRadius: 115, alignItems: 'center', justifyContent: 'center', backgroundColor: '#F8FAF7' },
  timerDisplay: { minWidth: 188, color: '#151A15', fontSize: 72, lineHeight: 76, fontWeight: '300', letterSpacing: -3, textAlign: 'center', fontVariant: ['tabular-nums'] },
  timerDisplayLong: { fontSize: 56, lineHeight: 62, letterSpacing: -2 },
  statusPill: { minHeight: 34, marginTop: 7, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, paddingHorizontal: 13, paddingVertical: 8, borderRadius: 999, backgroundColor: '#EAF6E4' },
  statusDot: { color: '#438C31', fontSize: 11 },
  statusText: { color: '#438C31', fontSize: 13, fontWeight: '800' },
  timerActions: { flexDirection: 'row', justifyContent: 'center', gap: 10 },
  primaryButton: { minWidth: 100, minHeight: 50, paddingHorizontal: 16, borderRadius: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, backgroundColor: '#76C457', shadowColor: '#76C457', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.25, shadowRadius: 10, elevation: 3 },
  primaryButtonText: { color: '#FFFFFF', fontSize: 14, fontWeight: '800' },
  dangerButton: { minWidth: 132, minHeight: 50, paddingHorizontal: 16, borderRadius: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, backgroundColor: '#FFF0F0' },
  dangerButtonText: { color: '#E05252', fontSize: 14, fontWeight: '800' },
  presets: { marginTop: 20, flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', gap: 8 },
  preset: { minHeight: 38, paddingHorizontal: 12, borderWidth: 1, borderColor: '#E2E8DF', borderRadius: 10, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFFFFF' },
  presetActive: { borderColor: '#76C457', backgroundColor: '#EAF6E4' },
  presetText: { color: '#697269', fontSize: 12, fontWeight: '800' },
  presetTextActive: { color: '#438C31' },
  presetPressed: { opacity: 0.7 },
  customEditor: { width: '100%', marginTop: 12, padding: 14, borderWidth: 1, borderColor: '#DCEBD5', borderRadius: 14, backgroundColor: '#FBFEF9' },
  customHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  customTitle: { color: '#151A15', fontSize: 13, fontWeight: '800' },
  customRange: { color: '#697269', fontSize: 11 },
  wheelRow: { marginTop: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'center' },
  wheelColumn: { flex: 1, alignItems: 'center' },
  wheelLabel: { marginBottom: 6, color: '#697269', fontSize: 11, fontWeight: '700' },
  wheelViewport: { width: '100%', height: 132, overflow: 'hidden', borderRadius: 14, backgroundColor: '#FFFFFF' },
  wheelScroll: { flex: 1 },
  wheelContent: { paddingVertical: 44 },
  wheelItem: { height: 44, alignItems: 'center', justifyContent: 'center' },
  wheelItemText: { color: '#B6C0B2', fontSize: 22, fontVariant: ['tabular-nums'] },
  wheelItemTextActive: { color: '#151A15', fontSize: 28, fontWeight: '800' },
  wheelSelection: { position: 'absolute', top: 44, left: 4, right: 4, height: 44, borderWidth: 1, borderColor: '#BFE4B2', borderRadius: 12, backgroundColor: 'rgba(234, 246, 228, 0.35)' },
  wheelSeparator: { width: 10, marginTop: 20, color: '#438C31', fontSize: 22, fontWeight: '800', textAlign: 'center' },
  customActions: { marginTop: 14, flexDirection: 'row', justifyContent: 'flex-end', gap: 8 },
  stopwatchInfo: { minHeight: 38, marginTop: 20, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 8, borderRadius: 10, backgroundColor: '#EAF6E4' },
  stopwatchInfoText: { color: '#438C31', fontSize: 12, fontWeight: '800' },
  smallPrimaryButton: { minHeight: 42, paddingHorizontal: 12, borderRadius: 11, alignItems: 'center', justifyContent: 'center', backgroundColor: '#76C457' },
  smallGhostButton: { minHeight: 42, paddingHorizontal: 12, borderWidth: 1, borderColor: '#E2E8DF', borderRadius: 11, alignItems: 'center', justifyContent: 'center' },
  ghostButtonText: { color: '#438C31', fontSize: 14, fontWeight: '800' },
  customError: { marginTop: 8, color: '#E05252', fontSize: 11 },
  focusCard: { width: '100%', marginTop: 24, paddingHorizontal: 16, paddingVertical: 15, borderWidth: 1, borderColor: 'rgba(226, 232, 223, 0.8)', borderRadius: 16, backgroundColor: '#FFFFFF', shadowColor: '#152914', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.06, shadowRadius: 10, elevation: 2 },
  focusHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  focusTitle: { color: '#151A15', fontSize: 14, fontWeight: '800' },
  focusSummary: { color: '#697269', fontSize: 13 },
  miniProgress: { width: '100%', height: 7, marginTop: 13, overflow: 'hidden', borderRadius: 20, backgroundColor: '#EDF1EB' },
  miniProgressFill: { width: '70%', height: '100%', borderRadius: 20, backgroundColor: '#76C457' },
  stopwatchProgressFill: { width: '100%', height: '100%', borderRadius: 20, backgroundColor: '#76C457' },
  stopwatchProgressEmpty: { width: 0, height: '100%', borderRadius: 20, backgroundColor: '#76C457' },
  focusFooter: { marginTop: 8, flexDirection: 'row', justifyContent: 'space-between' },
  focusFooterText: { color: '#697269', fontSize: 13 },
  buttonPressed: { opacity: 0.72, transform: [{ scale: 0.98 }] },
  disabledButton: { opacity: 0.48, shadowOpacity: 0, elevation: 0 },
})

export default styles
